# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6deae9ae430358a6f985593d707d75e861c4a247aa37813ac2e3d0250a20c3f7c551061bb65983d4b64ebbc5b3ace0140159ca9c6c6f76d22839975b873fd1f0

test:
  secret_key_base: 938ba5931dbb70c0b26007d6f131cd91dd15c672bcc2bb10e01199e2106c51b552e6696f90cbc7b226789c6473742134c59beebc42719dfb1084fd407a374783

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
